'use server';
/**
 * @fileOverview A flow for generating banner details from book information.
 *
 * - generateBanner - A function that generates a banner title and description.
 */

import { ai } from '@/ai/genkit';
import { GenerateBannerInput, GenerateBannerInputSchema, GenerateBannerOutput, GenerateBannerOutputSchema } from '@/lib/types';

const prompt = ai.definePrompt({
  name: 'generateBannerPrompt',
  input: { schema: GenerateBannerInputSchema },
  output: { schema: GenerateBannerOutputSchema },
  prompt: `You are a marketing expert for a bookstore. 
    Your task is to create a promotional banner for a specific book.
    Based on the book details provided, generate a compelling title and description for the banner.
    The tone should be exciting and persuasive, aiming to drive sales.

    Book Title: {{{bookTitle}}}
    Book Author: {{{bookAuthor}}}
    Book Description: {{{bookDescription}}}
    `,
});

const generateBannerFlow = ai.defineFlow(
  {
    name: 'generateBannerFlow',
    inputSchema: GenerateBannerInputSchema,
    outputSchema: GenerateBannerOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) {
      throw new Error('No output was generated by the model.');
    }
    return output;
  }
);

export async function generateBanner(
  input: GenerateBannerInput
): Promise<GenerateBannerOutput> {
  return generateBannerFlow(input);
}
